### ISSUE TITLE
Doesn't seem to work if checkbox is nested inside label?

### ISSUE THREAD

**Issue by ctolkien** [Wikiki/bulma-checkradio#1]
I'm not getting the checkbox to show if a label wraps the checkbox element.

**Comment by Wikiki** [comment]
Hi,

you're right it's a bug. I'll correct this soonly.

Thanks

**Comment by Wikiki** [comment]
Hi again,

sorry, but I had a look and unfortunately I can't design the label based on the input status (checked / unchecked) with the default Bulma structure.
So I have to use the following structure in order to have it working:

```html
<div class="field">
  <input class="is-checkbox" id="exampleCheckbox" type="checkbox" name="exampleCheckbox">
  <label for="exampleCheckbox">Check me</label>
</div>
```

**Comment by ctolkien** [comment]
Thanks for the update.

**Comment by michaelhamor** [comment]
I may be mistaken, but using the current documentation I ran into the same problem.  Tried this solution and it worked.

Does the bulma.io documentation need updating?

**Comment by Aadv1k** [comment]
It seems this issue still prevails! I am just leaving this comment here to get it noticed
