### ISSUE TITLE
When using is-block setting, the default checkbox is displayed

### ISSUE THREAD

**Issue by MangelMaxime** [Wikiki/bulma-checkradio#10]
The `is-block` seems like a good thing however, we should not display the default checkbox.

![image](https://user-images.githubusercontent.com/4760796/31610649-20e3f050-b279-11e7-90df-44d2cb06bb83.png)

Tested with:

- Firefox: 56.0 (32bits)
- Chromium: Version 60.0.3109.0 (Build de développement) (64 bits)

**Comment by Wikiki** [comment]
Fixed with ec81686fbf3ae5cb7bd11a71db216ce54f8e4432

**Comment by MangelMaxime** [comment]
Awesome thank you :)
