### ISSUE TITLE
Can't tab on input with keyboard

### ISSUE THREAD

**Issue by Frennetix** [Wikiki/bulma-checkradio#11]
When browsing with a keyboard you can't select any of the input, and thus, select a value.

**How to reproduce?** 

Go to https://wikiki.github.io/bulma-extensions/checkradio and press tab

**Comment by Frennetix** [comment]
Instead of _"display:none"_, I suggest this style:
```
.is-radio {
    display: inline-block;
    width: 0;
}
```

**Comment by Wikiki** [comment]
Fixed
