### ISSUE TITLE
Feature request: Indeterminate State

### ISSUE THREAD

**Issue by aocneanu** [Wikiki/bulma-checkradio#13]
Hi,

First, great job with all your bulma related repos. I've successfully used most of them :)

Could you add an indeterminate state for the checkboxes? I would contribute myself but your CSS level is stelar and mine is close to 0.

Thanks!

**Comment by Wikiki** [comment]
Hi,

what do you mean by "indeterminate state" ?

regards

**Comment by aocneanu** [comment]
In a situation where you have a parent checkbox control a group of checkboxes this state can reflect in the parent a partial selection from the group.

Check my particular case

![image](https://user-images.githubusercontent.com/16073274/32767587-b82a652a-c91c-11e7-9757-d1203469e8c2.png)

I would really like to upgrade this babies :)

Thanks.

**Comment by Wikiki** [comment]
Hi @aocneanu,

indeterminate state has been added ;-)

regards,

**Comment by aocneanu** [comment]
Sweet!

Btw, I like the new site, and the ability to manage all extensions with npm is also a good addition.

Thank you!

**Comment by Wikiki** [comment]
Thanks
