### ISSUE TITLE
Problem with modal scroll where using checkbox

### ISSUE THREAD

**Issue by xooler** [Wikiki/bulma-checkradio#14]
After click on checkbox in element with scroll there is something strange
It work in Chrome, in Firefox all right

Example - https://codepen.io/xooler/pen/LOjwod

Scroll modal content to this position:
![2017-11-15_18-37-37](https://user-images.githubusercontent.com/22120522/32844717-2d4d2ba4-ca34-11e7-85c2-ce71da5a4f0c.png)
And click on checkbox. After that in Chrome you see:
![2017-11-15_18-38-19](https://user-images.githubusercontent.com/22120522/32844781-484c2c7a-ca34-11e7-8623-8d77f2d873b6.png)

**Comment by xooler** [comment]
#15 this fix it

**Comment by Wikiki** [comment]
Thanks
