### ISSUE TITLE
Indeterminate state is not affected by the color modifiers

### ISSUE THREAD

**Issue by aocneanu** [Wikiki/bulma-checkradio#16]
Hi again,

It seems that the indeterminate state does not work with the color modifiers, nor with backgrounds.

If I put `is-danger` on a checkbox, the checked states is red but the indeterminate state goes back to the default color.

**Comment by Wikiki** [comment]
Hi,

it has been fixed by commit  c29f1f5.

Regards

**Comment by aocneanu** [comment]
This is the version that I use. You can see below the behaviour:

![indeterminate](https://user-images.githubusercontent.com/16073274/33233753-c3c40732-d223-11e7-9dfe-cc688d7d3112.gif)

**Comment by Wikiki** [comment]
The update has been done 1hour ago. Are you sure your version is up to date?
My tests were good.

**Comment by aocneanu** [comment]
Ah, you were talking about 91ea2bfbabc2c48ad4154e79f41c625402d8e46e :)

I clicked the link from you post. Will try now.

**Comment by Wikiki** [comment]
Sorry, wrong copy/paste for the commit number

**Comment by aocneanu** [comment]
Np, I figured. It works well now.

Thank you!
