### ISSUE TITLE
Add margin for inline checkradio

### ISSUE THREAD

**Issue by evilz** [Wikiki/bulma-checkradio#2]
Hi

Can you add some margin on two element that are inline.

Take a look here http://www.evilznet.com/Fable.Elmish.Bulma-checkradio/#elements/checkradio
Thank

**Comment by ctolkien** [comment]
Did this get fixed? I've a similar issue.

**Comment by Wikiki** [comment]
Hi @ctolkien,

this has been fixed by the Commit [#77854f1](https://github.com/Wikiki/bulma-checkradio/commit/77854f11b9a5e7cc08424fc3733449a7c49e7889)

Regards
