### ISSUE TITLE
Checkmark doesn't show in IE11

### ISSUE THREAD

**Issue by chenkie** [Wikiki/bulma-checkradio#22]
Looks like an issue with setting the `::after`. Any workarounds that you recommend?

**Comment by Wikiki** [comment]
Arf, I guess IE wants <code>:after</code> instead of <code>::after</code>.

I'll check that

**Comment by chenkie** [comment]
Awesome, thanks!

**Comment by chenkie** [comment]
Was this fixable in the end? Thanks!

**Comment by Wikiki** [comment]
Adding &:after for IE ;-)

**Comment by chenkie** [comment]
Thanks!
