### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Jvalal** [Wikiki/bulma-checkradio#26]
hi - can you do a from scratch tutorial, including the install, and updating the sass files? I'm new to all of this and I think there's a lot I'm missing and I can't figure it out. 

thanks

**Comment by Jvalal** [comment]
documentation isn't a tutorial. When you're fresh to this space we need a little more guidance.

**Comment by Wikiki** [comment]
Hi @Jvalal,

sorry there is no "tutorial" yet. Maybe you can look at the "calendar" extension demo page to find out how to integrate one of my extensions into your project.

I'll we do the same kind of documentation page for all other extensions when I'll find free time.
