### ISSUE TITLE
Add some dark and white colors ?

### ISSUE THREAD

**Issue by evilz** [Wikiki/bulma-checkradio#3]
Can you manage these colors

- White
- Light
- Dark
- Black

see here http://www.evilznet.com/Fable.Elmish.Bulma-checkradio/#elements/checkradio

**Comment by Wikiki** [comment]
Hi @evilz ,

you can use any color modifier provided by Bulma like is-dark, is-grey-dark, is-white, .....

Regards

**Comment by evilz** [comment]
Hi 

Yes may be just change the check inside the box black for white and light colors.
(checkbox only)

**Comment by Wikiki** [comment]
Can you please give me an example because if I test with is-dark modifier the check is white.

Regards
