### ISSUE TITLE
Override primary color using css

### ISSUE THREAD

**Issue by joselevelsup** [Wikiki/bulma-checkradio#38]
I'm struggling to change the primary color for the checkboxes and radio buttons. I already have it changed in my main css file for bulma. Any recommendations (using css. Not using sass)

**Comment by Wikiki** [comment]
Hi,

How did you do the change for the rest of your CSS ?
To replace it directly within the CSS file, just search and replace the hex value of primary color (#00d1b2)

**Comment by joselevelsup** [comment]
Hi, 
sorry for the late reply. For the change in the rest of my file, I just set the `.is-primary` class to be the color I want. Then I appended that `.is-primary` class to the checkbox element with the `.is-checkradio` class but still no color change. All this is done in my root (or global) css file.

**Comment by Wikiki** [comment]
Hi,

applying <code>is-primary</code> class to <code>is-checkradio</code> will not work. Colors are used on pseudo-elements <code>:before</code> and <code>:after</code>. If you don't want to edit the sass fil you have to manually find all <code>.is-primary</code> references from the min.css file of the extension to find all css rules using it and replacing the hex value.

**Comment by cilim** [comment]
@joselevelsup maybe this issue is tied to what I experienced. Described in issue https://github.com/Wikiki/bulma-checkradio/issues/51
