### ISSUE TITLE
Can't compile SASS file

### ISSUE THREAD

**Issue by pjeannenot** [Wikiki/bulma-checkradio#39]
It's not possible to compile the index SASS file for this component because there is a semicolon line 190 :

Error: 
Invalid CSS after \"...background, 5%)\": expected expression (e.g. 1px, bold), was \";\"\A on line 190 of ../node_modules/bulma-extensions/bulma-checkradio/src/sass/index.sass\A    ...

**Comment by Wikiki** [comment]
Fixed. Thanks to @Grummfy

**Comment by SjorsO** [comment]
@Wikiki Could you publish a new release that includes this fix?
