### ISSUE TITLE
Checkbox with no associated label

### ISSUE THREAD

**Issue by fariasfrancisco** [Wikiki/bulma-checkradio#5]
Is there any way I can place a checkbox with no label? As of now I am using a workaround with an empty label but I would rather not.

Thanks

**Comment by fariasfrancisco** [comment]
I would also like to know if there is way to move the label to the left of the checkbox.

**Comment by Wikiki** [comment]
Hi,

unfortunately label is mandatory to be able to have a pure CSS design.
Your workaround with an empty label is the right way to use it.

I'll see to add the possibility to have a left label display mode.

Regards

**Comment by Wikiki** [comment]
You can now use <code>is-rtl</code> modifier to get a left label design.

**Comment by fariasfrancisco** [comment]
Thanks!
