### ISSUE TITLE
Can't override colors due to package.json using minified css

### ISSUE THREAD

**Issue by cilim** [Wikiki/bulma-checkradio#51]
Hi everyone! 👋 Thanks for this library.

I would appreciate if you could change the [main attribute](https://github.com/Wikiki/bulma-checkradio/blob/master/package.json#L5) in _package.json_ and not use the distributions minified CSS file, but rather set it as the main lib [bulma](https://github.com/Wikiki/bulma/blob/master/package.json#L7) does.

The problem is that when I set up my libs like so:

```css
@import '~bulma/bulma';
@import 'bulma-checkradio';
@import 'theme';

@import 'components/menu';
@import 'components/navbar';
@import 'components/notices';
```

the primary color that I set in my main scss file, isn't taken into consideration (the primary color you set is used).

I have this fix in place for now, if it will help anyone out there:

```css
@import '~bulma/bulma';
@import 'bulma-checkradio/src/sass/index';
@import 'theme';

@import 'components/menu';
@import 'components/navbar';
@import 'components/notices';
```

**Comment by benjaminloeffel** [comment]
Thanks for this solution @cilim! 

It's a pity that the extension doesn't inherit the primary colour defined for Bulma or at least work with the option to add `is-primary` class to the input.

**Comment by Wikiki** [comment]
Main property in package.json has been updated and color are inherited from bulma core. See code from lines 226 and 337 of  `index.sass` file:

```sass
@each $name, $pair in $colors
    $color: nth($pair, 1)
    $color-invert: nth($pair, 2)
    &.is-#{$name}
```
