### ISSUE TITLE
Active effect when I have focus on a radio or checkbox

### ISSUE THREAD

**Issue by fariasfrancisco** [Wikiki/bulma-checkradio#6]
For example, when I'm using tab to move through elements in a form I have no way to tell if I'm currently focusing on a radio button or a checkbox.

Thanks in advence

**Comment by Wikiki** [comment]
Hi @fariasfrancisco ,

It should be fixed.
New variable added: $checkradio-focus-shadow

Regards,

**Comment by fariasfrancisco** [comment]
Great! Thanks!
