### ISSUE TITLE
Radio button misalignment

### ISSUE THREAD

**Issue by Markus-ipse** [Wikiki/bulma-checkradio#7]
The little highlight that indicates that a radio button is selected is not completely centered.
I think it might be due to some odd pixel rounding when it comes to its top and left position.

![image](https://user-images.githubusercontent.com/830794/30700564-30f94e80-9ee8-11e7-8957-152cfe618779.png)

My screen resolution and scaling, if it helps:
![image](https://user-images.githubusercontent.com/830794/30700770-d66c8206-9ee8-11e7-913a-0c57266aa5b9.png)

**Comment by Wikiki** [comment]
Hi @Markus-ipse ,

It should be fixed.

Regards,

**Comment by Markus-ipse** [comment]
It turns out there's still some slight alignment issues on small and medium
![image](https://user-images.githubusercontent.com/830794/30717565-832c0d48-9f1d-11e7-98ac-e811cc329612.png)

I think it's due to rounding errors, so I tried a different solution. Instead of setting the size of the ::after element with the mixin, I just use a transform: scale(0.5) on it instead. It seem to have solved the issue and it allowed me override less attributes for each size.
