### ISSUE TITLE
Cannot Create from SASS

### ISSUE THREAD

**Issue by alexfurr** [Wikiki/bulma-checkradio#70]
Get the following when compiling using node-sass. (Path to app changed to curly brackets)
`{
  "status": 1,
  "file": "/{PATH_TO_APP}/node_modules/bulma-checkradio/src/sass/index.sass",
  "line": 13,
  "column": 16,
  "message": "Invalid CSS after \"  $height: math\": expected expression (e.g. 1px, bold), was \".div($newSize, 2.5)\"",
  "formatted": "Error: Invalid CSS after \"  $height: math\": expected expression (e.g. 1px, bold), was \".div($newSize, 2.5)\"\n        on line 13 of node_modules/bulma-checkradio/src/sass/index.sass\n        from line 13 ofbulma.scss\n>>   $height: math.div($newSize, 2.5);\n\n   ---------------^\n"
}`

Not sure if it's related to issue 69 below.

**Comment by JakalGC** [comment]
same problem here. 
It doesn't like Math.div that have replace the division (/)
For example the line 13 was $height: $newSize / 2.5 and is now $height: math.div($newSize, 2.5)

**Comment by ansibleguy76** [comment]
Anyone fixed this ?  I have the same.
